// lib/constants.js — shared across server and client components.
// SEED_LISTINGS below is now superseded by the database (see schema.sql).
// ALTERNATIVES_POOL is still used client-side for the "we also considered"
// comparison until that logic is also moved server-side (a reasonable next
// iteration once real listing volume makes a static pool insufficient).

export const PLANS = {
  free: { name: "Free", searches: 8, price: 0, features: ["8 picks/day", "Top pick + alternatives", "Honest comparison"] },
  plus: { name: "Plus", searches: -1, price: 6, features: ["Unlimited picks", "Saved comparisons", "Price-drop alerts (soon)"] },
};

export const ALTERNATIVES_POOL = [
  { name: "REI Co-op Rainier rain jacket", price: "$110", note: "cheaper, heavier fabric, no pit zips", sponsored: false },
  { name: "Patagonia Torrentshell 3L", price: "$179", note: "similar weight, better known brand, less packable", sponsored: false },
  { name: "Arc'teryx Beta LT", price: "$400", note: "best-in-class but more than double the price for most hikers' needs", sponsored: false },
  { name: "Sony WH-CH720N", price: "$99", note: "cheaper, noticeably weaker ANC", sponsored: false },
  { name: "Sennheiser Accentum", price: "$179", note: "better mic quality, $50 more", sponsored: false },
  { name: "La Roche-Posay Anthelios", price: "$36", note: "stronger SPF formula, more expensive, slight white cast", sponsored: false },
  { name: "Osprey Talon 33", price: "$150", note: "more durable build, heavier, costs more", sponsored: false },
];

export const PRIVACY_POLICY = `Privacy Policy — SearchLLM.ai
Last updated: June 2026

1. WHAT THIS SITE DOES
SearchLLM.ai researches a product question, gives you one clear pick with reasoning, and shows the honest alternatives we did not pick and why. Some results include a brand we have an affiliate relationship with, tracked through a third-party network (Awin, Impact, or vCommission). We label every one of those clearly. We never let payment change which option we rank as the best pick — affiliate relationships only ever determine whether a tracked link appears below an honest recommendation that exists independently of payment.

2. WHAT WE COLLECT
Unregistered users: your query text for the current session only, never stored after the session ends. Registered users: email, hashed password, plan tier. We do not build a profile of your shopping history. We do not sell your data to brands or anyone else.

3. WHAT BRANDS RECEIVE
Brands that list with us never receive your identity, your query text, or any way to identify you individually. Click and sale tracking for affiliate links happens entirely inside Awin, Impact, or vCommission, the third-party networks we use — SearchLLM.ai does not operate its own tracking and does not itself collect or store click or conversion data tied to you.

4. HOW RECOMMENDATIONS ARE MADE
Every comparison is generated by an AI model evaluating publicly available product information. The model's instructions explicitly withhold any commission or payout information from the ranking process — it cannot favor a listing it has no financial data about. If you ever see something that looks off, you can flag it — every flag is reviewed by a person.

5. DATA RETENTION
Session data: deleted when your session ends. Account data: kept while your account is active, deleted within 30 days of account closure on request.

6. YOUR RIGHTS
Request deletion any time at privacy@searchllm.ai. We will confirm deletion within 30 days.

7. SECURITY
Encrypted in transit (TLS 1.3) and at rest (AES-256).

8. CHANGES
Registered users get 30 days' notice by email before any material change.`;

export const TERMS = `Terms of Use — SearchLLM.ai
Last updated: June 2026

1. WHAT YOU'RE AGREEING TO
By using SearchLLM.ai, registered or not, you agree to these terms.

2. WHAT THIS SERVICE IS
SearchLLM.ai gives AI-generated shopping research and product comparisons. It is not a retailer. We do not sell products directly. Checkout happens on the brand's own site.

3. HONEST RECOMMENDATION COMMITMENT
We commit to never ranking a sponsored product above an unsponsored one purely because of payment. Sponsored listings must still be genuinely relevant to your query to appear at all, and are always labeled. If we ever materially fail this commitment, you can report it to trust@searchllm.ai and we will investigate and respond within 5 business days.

4. AI-GENERATED CONTENT
Recommendations are generated by AI and may contain errors, including pricing or availability that has changed since generation. Always verify price and availability on the brand's own checkout page before buying.

5. FREE AND PAID PLANS
Free plan: 8 picks per day, resetting at 00:00 UTC. Plus plan: unlimited picks, billed monthly, cancel anytime effective at the end of the billing period.

6. BRAND LISTINGS
Brands may submit products for a paid affiliate placement, subject to human review before going live. SearchLLM is not a party to any transaction between you and a brand and is not responsible for product quality, shipping, or returns — that is the brand's responsibility under their own terms.

7. PROHIBITED USE
No scraping, no reverse engineering the recommendation model, no abuse of the free-tier quota through automation.

8. DISCLAIMERS
Provided "as is." We are not liable for purchase decisions made based on our recommendations — we give you the research, the decision is yours.

9. CONTACT
legal@searchllm.ai · trust@searchllm.ai for honesty concerns specifically.`;
